dist: focal
sudo: true
language: ruby
rvm:
  - 2.7.1

before_script:
 - ruby -v
  
script:
 - JEKYLL_ENV=production bundle exec jekyll build
 - bundle exec htmlproofer ./build --empty-alt-ignore --disable_external

cache: bundler

notifications:
  email:
    recipients:
      - jeff@langrsoft.com
      - john@smartypixels.com
    on_success: change
    on_failure: always
