dist: focal
sudo: true
language: ruby
rvm:
  - 2.7.1

script:
 - JEKYLL_ENV=production bundle exec jekyll build
 - bundle exec htmlproofer ./build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email:
    recipients:
      - john@smartypixels.com
      - johnernsthausen@gmail.com
    on_success: change
    on_failure: always
