plugins:
  - jekyll-assets

# Structure configuration
# source: source
destination: build

sass:
    sass_dir: _sass

assets:
  js_compressor:  uglifier
  compressors:
    uglifier:
      harmony: true
      compress:
        unused: false
  external:
      uglifier:
        harmony: true
  css_compressor: sass
  cachebust: soft
  sources:
    - assets/images/home
    - assets/images/banner
    - assets/images/blog
    - assets/images/books
    - assets/images/design
    - assets/images/ico
    - assets/images/manual
    - assets/javascripts
    - assets/stylesheets

# Site settings
title: WARNING! DO THIS ON EACH PAGE
description: WARNING! TAG ON EACH PAGE
url: "http://pubmob.com"
permalink: /:year/:month/:day/:title/
twitter: https://twitter.com/pubmobdotcom
github: https://github.com/pubmob-com
appointment: 
facebook: https://www.facebook.com/PubMob-110341337369334/
email:
  address: info@langrsoft.com
  subject: mailto:info@langrsoft.com?subject=pubmob%20inquiry
phone:
  actual: 
  reference: 
address:
  name: PubMob
  address: P.O. Box 6884
  city: Colorado Springs
  state: CO
  zipcode: 80934-6884
  country: United States
breakpoint-mobile: 500px;
breakpoint-tablet: 830px;
breakpoint-desktop: 960px;
breakpoint-max: 1080px;

# Build settings
encoding: utf-8

navigation:
  - title: Home
    url: /
    id: navhome
  - title: Virtual Pubs
    url: /pubs
    id: navpubs
  - title: On Tap
    url: /offerings
    id: navofferings
  - title: About
    url: /about
    id: navabout

collections:
  pubs:
    output: true
  offerings:
    output: true
  announcements:
    output: false

session-lead-term: session lead
session-lead-term-plural: session leads
